### PR TITLE
BaSP-TG-62: Filter Search Shared Component.

### PR DESCRIPTION
**Pull request by Gearyandres94**
Search

### CODE REVIEW

**Review by FiolAxel — APPROVED** [review]

**Review by Facund0Fernandez — COMMENTED** [review]
Maybe the border color could be #373867 and less radius.

**Review by Facund0Fernandez — APPROVED** [review]

**Review by GuidoCerioni — COMMENTED** [review]
Nice work! Try to use camelCase on css classes

**Review by Facund0Fernandez — APPROVED** [review]

**Review by GuidoCerioni — APPROVED** [review]
Nice work Andy!

**Comment by AlejandroSantini** [comment]
Jood job!

**Review by AlejandroSantini — APPROVED** [review]
Good job!

**Pull request merged**
